### ISSUE TITLE
`endianess` return type

### ISSUE THREAD

**Issue by leonskij** [denosaurs/byte_type#1]
The [`endianess`] function currently returns a boolean; wouldn't it be better to use an enum here so that it's more clear what is being returned?

I could make a quick PR for this if you'd like me to.

[`endianess`]: https://github.com/denosaurs/byte_type/blob/main/mod.ts#L18

**Comment by eliassjogreen** [comment]
The design decision that was made was to match the [`DataView`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView) endianess boolean where `true` is little endian mostly to conform and not stray away too far from the web standard api which we use under the hood.

**Comment by leonskij** [comment]
Ah, coolio. I completely forgot that this issue even existed and what you said makes sense.

**Comment by eliassjogreen** [comment]
Me too! Found it when I was looking through my issues on GitHub and saw I hadn't answered, my bad!
