### ISSUE TITLE
add missing short types

### ISSUE THREAD

**Issue by shevernitskiy** [denosaurs/byte_type#18]
I planned to parse PE headers, that contains 2-4 bit fields, but lib missing those types. I suggest to add it:)

**Comment by eliassjogreen** [comment]
Sure that sounds like a good idea! I suggest the following new types be added:

- [ ] `U2`
- [ ] `I2`
- [ ] `U4`
- [ ] `I4`

This should be a rather easy issue to solve and get started with, I won't have to implement it for a little while but as a pointer for the person that decides to implement it:

#### Read

1. `dataView.getUint8`
3. Bitmask the relevant 2 or 4 bits
4. [If it is a signed integers it is two's complement](https://en.wikipedia.org/wiki/Two%27s_complement) convert it from unsigned to signed then

#### Write

Writing is the same but in reverse.

**Comment by MierenManz** [comment]
@eliassjogreen does it make sense to have a 2 bit and 4 bit int value? Bitfield I can get. But I don't really see the use for a signed `0 | 1` or a signed 0 to 7?

**Comment by eliassjogreen** [comment]
I mean the use is mostly for parsing things like file headers and other such things. But I also don't see any issue implementing it if there is a use for it and it doesn't damage the rest of the module.

**Comment by nhrones** [comment]
I can understand supporting `nibble` (4-bits) but 2-bits?

**Comment by eliassjogreen** [comment]
It's very much an esoteric thing I guess, but maybe if someone has 4x 2-bits packed together for stuff like ternary choices (yes, no, maybe)?

**Comment by MierenManz** [comment]
How would these eve be implemented? I assume it just consumed a full byte? Because it's pretty hard to read 1.25 bytes for example

**Comment by eliassjogreen** [comment]
Yeah, you're right. I was thinking adding support for quarter bytes using floats and shifting but that is probably just a mess.

**Comment by MierenManz** [comment]
If someone needs to have a compound type that uses bit indices then I feel like we should help them write that component, but I don't think we should have it in byte_type itself. It feels like such a unique case that only one or two people will need it.

**Comment by eliassjogreen** [comment]
Yep, agreed. Closing the issue
